services:
  - type: web
    name: kpn-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
